apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azure-file-static
  labels:
    app.kubernetes.io/name: csi-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: file.csi.azure.com
    readOnly: false    
    volumeHandle: csi-test-109223           # [UNIQUE_VOLUME_ID] - make sure this volumeid is unique in the cluster. `#` is not allowed in self defined volumeHandle
    volumeAttributes:
      resourceGroup: demo  
      storageAccount: demostorageubs #tried storageAccountName, accountName, storageName, azureStorageAccountName
      shareName: sample1              # [EXISTING_FILE_SHARE_NAME] - only file share name, don't use full path
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-file-static
  labels:
    app.kubernetes.io/name: csi-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-azure-file-static
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: 1-azure-file-static
  labels:
    app.kubernetes.io/name: csi-test
spec: 
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-test
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: busybox
        image: busybox:1.30.1
        args: ["/bin/sh", "-ec", "SLEEP_TIMEOUT=60;while :; do echo sleeping for $SLEEP_TIMEOUT seconds...; sleep $SLEEP_TIMEOUT ; done"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: azure-file-static
          mountPath: /data
      volumes:
      - name: azure-file-static
        persistentVolumeClaim:
          claimName: pvc-azure-file-static
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: 2-azure-file-static
  labels:
    app.kubernetes.io/name: csi-test
spec: 
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-test
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: busybox
        image: busybox:1.30.1
        args: ["/bin/sh", "-ec", "SLEEP_TIMEOUT=3600;while :; do echo sleeping for $SLEEP_TIMEOUT seconds...; sleep $SLEEP_TIMEOUT ; done"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: azure-file-static
          mountPath: /data
      volumes:
      - name: azure-file-static
        persistentVolumeClaim:
          claimName: pvc-azure-file-static